[package]
name = "bevy_sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", default-features = false, features = ["multi_threaded"] }
sqlx = { version = "*", features = ["runtime-async-std", "sqlite"] }

[dev-dependencies]
rand = "*"
bevy-inspector-egui = "*"

[[example]]
name = "minimal"
required-features = ["bevy/bevy_winit"]

[[example]]
name = "sqlite"
required-features = ["bevy/bevy_winit"]
